### ISSUE TITLE
Deep clone does not lead to a complete copy

### ISSUE THREAD

**Issue by jakob-r** [r-lib/R6#133]
Consider the following example
```r
library(R6)

FooClass = R6Class(
  "Foo",
  public = list(
    initialize = function(value) {
      # force(value) # does not help
      self$foo.fun = function(x) x == value
    },
    foo.fun = NULL
  )
)

foo.obj1 = FooClass$new(3)
foo.obj1$foo.fun(3)
# TRUE

foo.obj2 = foo.obj1$clone()
foo.obj2$foo.fun(3)
# value not found

foo.obj3 = foo.obj1$clone(deep = TRUE)
foo.obj3$foo.fun(3)
# value not found
```

Or is this expected to fail?

**Comment by wch** [comment]
That is the expected behavior - the `clone()` method assumes that any function in the object (like `foo.fun` in this case) is a method, and when it makes the copy of that function in the clone object, it reassigns the function's environment so that it can find the appropriate `self` object.

Your version of the `foo.fun` captures the environment from the `initialize` method, but that environment gets lost in the cloning process. In this particular case, you'd be better off storing `value` in `self` or `private` instead of capturing it with a closure, but that may or may not be appropriate for your real use case.

This is essentially the same issue as #94.

I think this the documentation should probably do a better job explaining how cloning works.

**Comment by jakob-r** [comment]
Thanks for your comprehensible answer. That solves the issue for me.
