### ISSUE TITLE
Vignettes not showing up on CRAN

### ISSUE THREAD

**Issue by daattali** [r-lib/R6#177]
I just Googled for "r6 r" to remind myself of the general API (in hindsight, that's a terrible search term...) and the third result was what I wanted: the introduction vignette at this URL https://cran.r-project.org/package=R6/vignettes/Introduction.html

Unfortunately that page currently returns a 404. It looks like on CRAN, none of the package vignettes exist. Perhaps this was done on purpose, and Google results will update in time, but in case this is not on purpose I wanted to let you know.

**Comment by wch** [comment]
That's weird that it still comes up in the search -- that went away a few months ago. I intentionally moved the documentation from vignettes to https://r6.r-lib.org/, because the package was 315 kB, 90% of which was vignettes. Now it's 31 kB.

I think it does make sense to change the DESCRIPTION to link to https://r6.r-lib.org/ instead of the github page, though.

**Comment by wch** [comment]
Oh, it looks like the dev version already links to https://r6.r-lib.org/ (that was issue #161).
